### ISSUE TITLE
PECL exts using real_name are not found by pecl.php.net

### ISSUE THREAD

**Issue by cmb69** [php/web-rmtools#11]
Consider pecl_http (which appears to be the only maintained PECL extension using `real_name`):
https://github.com/php/web-rmtools/blob/6a54106837758ad96d8ff53ef1bfd2433c6e7f66/data/config/pecl/exts.ini#L242-L243
The build artifacts are currently named `php_http-*.zip` and are uploaded to a `http` folder. However, pecl.php.net expects the binary packages to be `pecl_http/php_pecl_http-*`. One issue is `PECLExt::getPackageName()`:
https://github.com/php/web-rmtools/blob/6a54106837758ad96d8ff53ef1bfd2433c6e7f66/include/PeclExt.php#L172-L175
`$this->name` is the `real_name` ("http"), but would have to be the original extension name ("pecl_http"). Another issue is the upload target folder:
https://github.com/php/web-rmtools/blob/6a54106837758ad96d8ff53ef1bfd2433c6e7f66/script/pecl.php#L330
`PECLExt::getName()` again returns the `real_name` ("http") instead of the original extension name ("pecl_http").

Alternative solutions would be to adapt the respective code in php/web-pecl, or maybe even to drop support for real_name altogether and require packages to have a single name.

What do you think @weltling?

PS: see also m6w6/ext-http#97

**Comment by m6w6** [comment]
It had to be named ˋpecl_httpˋ because there also was a PEAR package with the name ˋhttpˋ.

Just a little history, IIRC.

**Comment by cmb69** [comment]
This PR can be closed, since we're going to archive this repo anyway.
