### ISSUE TITLE
Archive this repo?

### ISSUE THREAD

**Issue by cmb69** [php/web-rmtools#22]
This should finally decided on the appropriate mailing list (likely internals-win), but I'm asking here first; if there are objections, there's probably no need for further discussion.

Despite the name and description of this repo, the code has only been used to drive the Windows builds of PHP on the discontinued build machines, and to drive the Windows builds of PECL extensions on the defunct PECL build machine. So it is unlikely the code is still used; possibly by some users, but even that seems unlikely.

And given that we have https://github.com/php/php-windows-builder, I don't think that this repo will be revived (especially since the whole build process doesn't appear to be contemporary).

Any objections against archiving this repo? @shivammathur?

**Comment by shivammathur** [comment]
@cmb69 No objections from me.

**Comment by Jan-E** [comment]
Never used it. No objections,

**Comment by cmb69** [comment]
There have been no replies to my messages to the respective mailing lists (https://news-web.php.net/php.internals.win/1280 and https://news-web.php.net/php.webmaster/31887) for a week, so I think we can proceed. If someone steps up later, we could still un-archive.
