### ISSUE TITLE
snap builder is locale dependend

### ISSUE THREAD

**Issue by cmb69** [php/web-rmtools#5]
snapshot_task.bat uses the pseudo environment variables `%date%` and `%time%` to construct a timestamp for the log files. To correctly work, this requires the machine to use an English locale; otherwise the timestamp is broken (e.g. with a German locale is could be `13-03-2019_42-25` instead of `2019-03-22_13-42-25`). Even worse, at least some locales will contain a comma, so that snap.bat will effectively be called with an additional parameter, as such setting force mode. For instance, calling `snapshot_task.bat --task-args "php72 nts-windows-vc15-x64"` with a German locale, will call something like `snap.bat php72 nts-windows-vc15-x64  ,14-..log`.

We should either determine the timestamp in a locale independend manner, or require an English locale.

**Comment by weltling** [comment]
Good catch. Perhaps one could yous powershell for that? Otherwise, not sure by we might use the PHP contained in the binary SDK, as it's required anyway.

Thanks.

**Comment by cmb69** [comment]
https://stackoverflow.com/questions/10945572/windows-batch-formatted-date-into-variable#answer-28250863 lists a bunch of options. If we're concerned that powershell would not be available, a simple JScript script would also be an option. And, yeah, we could also use PHP.

**Comment by weltling** [comment]
Powershell should be available on the build host, actually. Not critical what is used of those three, anyway, but fixing this would be ofc nice :)

Thanks.

**Comment by cmb69** [comment]
Fixed with 6baf0ef19d94b0d10bb0bdc52e01958e8adb99ce.
